### ISSUE TITLE
Use optional locale in getCurrency when available

### ISSUE THREAD

**Issue by Sector14** [ozum/intl-data#1]
The currency code has the locale "tr-TR" hard-coded for all conversions. 

`const textWithNumbers = (0).toLocaleString("tr-TR", { ...commonOptions, currencyDisplay: "symbol" }).replace(",", ""); // "OMR 0000" or "$000" or "RWF 0" or "0000 OMR"... without decimal separator
`
This leads to a discrepancy when other UI code is making use of Intl.NumberFormat for example

```
new Intl.NumberFormat("zh-CN", { style: 'currency', currency: "CNY" }).format(1000)
"￥1,000.00"
new Intl.NumberFormat("zh-TW", { style: 'currency', currency: "CNY" }).format(1000)
"CN¥1,000.00"
new Intl.NumberFormat("tr-TR", { style: 'currency', currency: "CNY" }).format(1000)
"CN¥1.000,00"
```
Could the optional locale that is passed into getCurrency be used instead with a fall back to "tr-TR" when not set? For example: 

```
  // Compute currency data
  if (currencyCache[currencyCode] === undefined) {
    const localeOverride = locale ? locale : "tr-TR"
    const textWithNumbers = (0).toLocaleString(localeOverride, { ...commonOptions, currencyDisplay: "symbol" }).replace(",", ""); // "OMR 0000" or "$000" or "RWF 0" or "0000 OMR"... without decimal separator

    // eslint-disable-next-line no-irregular-whitespace
    if ((0).toLocaleString(localeOverride, { ...commonOptions, currencyDisplay: "name" }).includes(currencyCode)) {
      throw new Error(`Invalid currency code: ${currencyCode}.`);
    }
```

I was going to submit a pull request but there is a little more to this change than just the above.

The "Compute currency name in given locale" would now run regardless of whether you actually want the output of that or not. Adding a param to make this optional again would be a breaking change as far as any existing users are concerned. 

Also the cache probably wants to be based on the locale and code rather than just code. 

Edit: Removed the comment about tests failing. I had an poorly VM which has now been resolved :)

**Comment by ozum** [comment]
@Sector14 thanks for reporting. Actually `tr-TR` is not used for conversion but for calculation, and it was not the cause of the issue.

Problem was, I assumed same currency has same sign in every locale.

I updated and published a new version. Could you please check if it works as you expected.

**Comment by Sector14** [comment]
Checked and can confirm it's fixed. Thanks.
