### ISSUE TITLE
decimalCharacter null for es-CO

### ISSUE THREAD

**Issue by Sector14** [ozum/intl-data#2]
When using the es-CO locale (and it seems "es" too) the decimalCharacter will be returned as undefined. In addition the returned group separator is actually the decimal character.

```
  [digitGroupSeparator, decimalCharacter] = (1111.11).toLocaleString("es-CO").replace(/1/g, "");

  result: ","
```

```
  [digitGroupSeparator, decimalCharacter] = (11111.11).toLocaleString("es-CO").replace(/1/g, "");
  result: ".,"
```

It seems the test string isn't quite long enough for es-CO to trigger group separation and thus only "," is returned. 

It may be that the returned array needs to be made unique if the "1111.11" string is extended too much further however as there's a risk of getting "..," returned. Or perhaps the test split into two individual lines:

```
  const digitGroupSeparator = (1111111111).toLocaleString("es-CO").replace(/1/g, "");
  const decimalCharacter = (1.11).toLocaleString("es-CO").replace(/1/g, "");
```

I'm not familiar with enough locales to say which may be the most appropriate solution, so I've raised this as an issue rather than pull request for your consideration.

**Comment by ozum** [comment]
Thanks for reporting. `11111.1` seems sufficient. I updated the library and it seems working as expected now. Please check the latest version.
